apiVersion: v1
kind: Service
metadata:
  name: transport-app-service
  labels:
    app: transport-app
spec:
  type: NodePort
  selector:
    app: transport-app
  ports:
  - name: http
    port: 80
    targetPort: 5001
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: transport-app-internal
  labels:
    app: transport-app
spec:
  type: ClusterIP
  selector:
    app: transport-app
  ports:
  - name: http
    port: 5001
    targetPort: 5001
    protocol: TCP
